// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"microservice-demo-go/pongservice/config"
	"microservice-demo-go/pongservice/genproto/v1"
	"microservice-demo-go/pongservice/service"
)

// Injectors from wire.go:

// InitServer Inject service's component
func InitServer(conf *config.Config) (v1.PongServiceServer, error) {
	pongServiceClient, err := service.NewClient(conf)
	if err != nil {
		return nil, err
	}
	pongServiceServer := service.NewServer(conf, pongServiceClient)
	return pongServiceServer, nil
}
